--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 10.0.1006
--   Created On : quinta-feira, 21 setembro, 2017 
--   DBMS       : PostgreSQL 
--   -------------------------------------------------- 





--  Create Tables 
CREATE TABLE banco ( 
	id smallint NOT NULL,
	nome varchar(50)
)
;

CREATE TABLE cheque ( 
	id integer NOT NULL,
	numero bigint NOT NULL,
	id_banco smallint NOT NULL,
	id_pessoa smallint NOT NULL,
	valor numeric(10,2) NOT NULL,
	tipo smallint NOT NULL,
	data_cadastro timestamp,
	data_desconto timestamp,
	data_entrada timestamp,
	observacao text,
	sem_fundo boolean NOT NULL
)
;

CREATE TABLE empresa ( 
	id smallint NOT NULL,
	id_pessoa smallint NOT NULL,
	usuario varchar(20) NOT NULL,
	senha varchar(20) NOT NULL
)
;

CREATE TABLE pessoa ( 
	id smallint NOT NULL,
	nome varchar(50) NOT NULL,
	tipo smallint NOT NULL,
	cpf_cnpj varchar(14),
	inscricao_estadual varchar(20),
	fone varchar(20),
	email varchar(50),
	data_cadastro timestamp NOT NULL
)
;

CREATE TABLE repasse ( 
	id integer NOT NULL,
	id_cheque integer,
	datahora timestamp NOT NULL,
	id_pessoa smallint NOT NULL
)
;


--  Create Primary Key Constraints 
ALTER TABLE banco ADD CONSTRAINT PK_banco 
	PRIMARY KEY (id)
;


ALTER TABLE cheque ADD CONSTRAINT PK_cheque 
	PRIMARY KEY (id)
;


ALTER TABLE empresa ADD CONSTRAINT PK_empresa 
	PRIMARY KEY (id)
;


ALTER TABLE pessoa ADD CONSTRAINT PK_pessoa 
	PRIMARY KEY (id)
;


ALTER TABLE repasse ADD CONSTRAINT PK_repasse 
	PRIMARY KEY (id)
;




--  Create Foreign Key Constraints 
ALTER TABLE cheque ADD CONSTRAINT FK_cheque_pessoa 
	FOREIGN KEY (id_pessoa) REFERENCES pessoa (id)
;

ALTER TABLE empresa ADD CONSTRAINT FK_empresa_pessoa 
	FOREIGN KEY (id_pessoa) REFERENCES pessoa (id)
;

ALTER TABLE repasse ADD CONSTRAINT FK_repasse_cheque 
	FOREIGN KEY (id_cheque) REFERENCES cheque (id)
;

ALTER TABLE repasse ADD CONSTRAINT FK_repasse_pessoa 
	FOREIGN KEY (id_pessoa) REFERENCES pessoa (id)
;
